### PR TITLE
You forgot old man

### PR DESCRIPTION
**Pull request by xamionex**
Yeah. This stops net_chan :)

### CODE REVIEW

**Comment by RomeoCantCode** [comment]
are you sure its not used anymore?

**Comment by xamionex** [comment]
> are you sure its not used anymore?

Yes, Didn't you set it to change via bool?

**Comment by RomeoCantCode** [comment]
ummm no I don't think so

**Comment by RomeoCantCode** [comment]
isn't that thing you mean that it actually got converted to bool by accident?

**Comment by xamionex** [comment]
> isn't that thing you mean that it actually got converted to bool by accident?

0a5fe0d010b81e9cf407611cd955cfcd1b0a3fc7

You change it via button, so replace is no longer needed

**Comment by RomeoCantCode** [comment]
I am really confused, will check if I got some sleep lmao

**Comment by xamionex** [comment]
Tested it, works fine on fresh config

**Comment by RomeoCantCode** [comment]
ooh right thanks for linking the commit, your PR title is 100% correct

**Pull request merged**
